# Generated by Django 5.1.7 on 2025-03-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mdbfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdbfile',
            name='status',
        ),
        migrations.AddField(
            model_name='mdbfile',
            name='created_data',
            field=models.IntegerField(default=0),
        ),
    ]
