# Generated by Django 5.1.7 on 2025-05-28 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_conectores_conexiones_tipocable_adapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adapterpinmap',
            name='test_connector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_mapped_pins', to='home.adapterconnector'),
        ),
        migrations.AlterField(
            model_name='adapterpinmap',
            name='to_test_pin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
