# Generated by Django 5.1.7 on 2025-03-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_mdbfile_status_mdbfile_created_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mdbfile',
            old_name='created_data',
            new_name='created_records',
        ),
    ]
