# Generated by Django 5.1.7 on 2025-05-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_adapterpinmap_test_connector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='conector_dest_type',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='conector_orig_type',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
