# Generated by Django 5.1.7 on 2025-03-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_created_data_mdbfile_created_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conectores',
            fields=[
                ('idconector', models.IntegerField(db_column='IDConector', primary_key=True, serialize=False)),
                ('conector', models.TextField(blank=True, db_column='Conector', null=True)),
                ('link', models.TextField(blank=True, db_column='Link', null=True)),
                ('codigovuelo', models.TextField(blank=True, db_column='CodigoVuelo', null=True)),
                ('codigoingenieria', models.TextField(blank=True, db_column='CodigoIngenieria', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('link_file', models.TextField(blank=True, db_column='link_file', null=True)),
                ('listadepines', models.TextField(blank=True, db_column='ListadePines', null=True)),
                ('codigopinvuelo', models.TextField(blank=True, db_column='CodigoPinVuelo', null=True)),
                ('codigopiningenieria', models.TextField(blank=True, db_column='CodigoPinIngenieria', null=True)),
                ('datasheet', models.TextField(blank=True, db_column='datasheet', null=True)),
            ],
            options={
                'db_table': 'Conectores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conexiones',
            fields=[
                ('field_de_señal', models.IntegerField(db_column='# de Señal', primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, db_column='Nombre', null=True)),
                ('tipo_señal', models.TextField(blank=True, db_column='Tipo Señal', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripción', null=True)),
                ('señal_unidad', models.TextField(blank=True, db_column='Señal Unidad', null=True)),
                ('sistema', models.TextField(blank=True, db_column='Sistema', null=True)),
                ('subsistema', models.TextField(blank=True, db_column='Subsistema', null=True)),
                ('unidad', models.TextField(blank=True, db_column='Unidad', null=True)),
                ('modulo', models.TextField(blank=True, db_column='Modulo', null=True)),
                ('in_out', models.TextField(blank=True, db_column='IN/OUT', null=True)),
                ('origen', models.TextField(blank=True, db_column='Origen', null=True)),
                ('conector_orig', models.TextField(blank=True, db_column='Conector Orig', null=True)),
                ('pin_orig', models.TextField(blank=True, db_column='Pin Orig', null=True)),
                ('tipo_de_con_orig', models.TextField(blank=True, db_column='Tipo de Con Orig', null=True)),
                ('awg', models.TextField(blank=True, db_column='AWG', null=True)),
                ('longitud', models.TextField(blank=True, db_column='Longitud', null=True)),
                ('manguera', models.TextField(blank=True, db_column='Manguera', null=True)),
                ('shield', models.TextField(blank=True, db_column='Shield', null=True)),
                ('twisted', models.TextField(blank=True, db_column='Twisted', null=True)),
                ('señal_unidad1', models.TextField(blank=True, db_column='Señal Unidad1', null=True)),
                ('sistema1', models.TextField(blank=True, db_column='Sistema1', null=True)),
                ('subsistema1', models.TextField(blank=True, db_column='Subsistema1', null=True)),
                ('unidad1', models.TextField(blank=True, db_column='Unidad1', null=True)),
                ('modulo1', models.TextField(blank=True, db_column='Modulo1', null=True)),
                ('in_out1', models.TextField(blank=True, db_column='IN/OUT1', null=True)),
                ('destino', models.TextField(blank=True, db_column='Destino', null=True)),
                ('conector_dest', models.TextField(blank=True, db_column='Conector Dest', null=True)),
                ('pin_dest', models.TextField(blank=True, db_column='Pin Dest', null=True)),
                ('tipo_de_con_dest', models.TextField(blank=True, db_column='Tipo de Con Dest', null=True)),
                ('obsev', models.TextField(blank=True, db_column='Obsev', null=True)),
                ('interface', models.TextField(blank=True, db_column='Interface', null=True)),
                ('frec', models.TextField(blank=True, db_column='Frec', null=True)),
                ('imax', models.TextField(blank=True, db_column='Imax', null=True)),
                ('drop_voltage', models.TextField(blank=True, db_column='Drop Voltage', null=True)),
                ('clase_emi_emc', models.TextField(blank=True, db_column='Clase EMI/EMC', null=True)),
                ('clase_repuesto_field', models.TextField(blank=True, db_column='Clase(Repuesto)', null=True)),
                ('integrada_si_no_field', models.TextField(blank=True, db_column='Integrada(si/no)', null=True)),
                ('documento', models.TextField(blank=True, db_column='Documento', null=True)),
                ('activo_si_no_field', models.TextField(blank=True, db_column='activo(si/no)', null=True)),
                ('observacion_activo_si_no_field', models.TextField(blank=True, db_column='Observacion(activo si/no)', null=True)),
                ('PEM_Polaridad', models.TextField(blank=True, db_column='PEM_Polaridad', null=True)),
                ('PEM_Telemetria', models.TextField(blank=True, db_column='PEM_Telemetria', null=True)),
                ('PEM_tipo_señal', models.TextField(blank=True, db_column='PEM_tipo_señal', null=True)),
            ],
            options={
                'db_table': 'Conexiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocable',
            fields=[
                ('idcable', models.IntegerField(db_column='IDCable', primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, db_column='Nombre', null=True)),
                ('nombrecable', models.TextField(blank=True, db_column='NombreCable', null=True)),
                ('nombrealambre', models.TextField(blank=True, db_column='NombreAlambre', null=True)),
                ('de', models.TextField(blank=True, db_column='DE', null=True)),
                ('tamaño', models.TextField(blank=True, db_column='Tamaño', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('radiomincurvatura', models.TextField(blank=True, db_column='RadioMinCurvatura', null=True)),
            ],
            options={
                'db_table': 'TipoCable',
                'managed': False,
            },
        ),
    ]
