# Generated by Django 5.1.7 on 2025-06-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testresult_conector_dest_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='connector_type',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teststage',
            name='connector_type',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
