# Generated by Django 5.1.7 on 2025-03-27 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_conectores_conexiones_tipocable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector', models.CharField(max_length=50)),
                ('test_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En curso'), ('completed', 'Terminado')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveIntegerField()),
                ('connector_dest', models.CharField(max_length=50)),
                ('instructions', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Terminado')], default='pending', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='home.testsession')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_id', models.IntegerField()),
                ('signal_name', models.CharField(max_length=50)),
                ('pin_a', models.IntegerField()),
                ('pin_b', models.IntegerField()),
                ('min_exp_value', models.FloatField(blank=True, null=True)),
                ('max_exp_value', models.FloatField(blank=True, null=True)),
                ('measured_value', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='home.teststage')),
            ],
        ),
    ]
