# Generated by Django 5.1.7 on 2025-06-05 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_testsession_connector_type_teststage_connector_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adapterpinmap',
            name='pxi_connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adapter_mapped_pxi_pins', to='home.adapterconnector'),
        ),
        migrations.AlterField(
            model_name='adapterpinmap',
            name='test_connector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adapter_mapped_test_pins', to='home.adapterconnector'),
        ),
    ]
