# Generated by Django 5.1.7 on 2025-06-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_adapterpinmap_pxi_connector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='test_type',
            field=models.CharField(choices=[('Pin a chasis', 'Pin a chasis'), ('Pin a otros', 'Pin a otros'), ('Entre par de pines', 'Entre par de pines'), ('Pin a pin', 'Pin a pin')], max_length=50),
        ),
    ]
