# Generated by Django 5.1.7 on 2025-03-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_testsession_teststage_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='pin_a',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='pin_b',
            field=models.CharField(max_length=50),
        ),
    ]
