# Generated by Django 5.1.7 on 2025-06-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_testsession_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adapter',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
