# Generated by Django 5.1.7 on 2025-03-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_testresult_pin_a_alter_testresult_pin_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='conector_dest',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='conector_orig',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
