# Generated by Django 5.1.7 on 2025-03-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_testresult_conector_dest_testresult_conector_orig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='max_exp_value',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testresult',
            name='measured_value',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testresult',
            name='min_exp_value',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
