# Generated by Django 5.1.7 on 2025-07-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_globalconfig_delete_connectionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='signal_type',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
