# Generated by Django 5.1.7 on 2025-04-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_testresult_max_exp_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststage',
            name='stage_type',
            field=models.CharField(default='reference', max_length=50),
            preserve_default=False,
        ),
    ]
