# Generated by Django 5.1.7 on 2025-04-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_teststage_stage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='measured_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('pass', 'OK'), ('fail', 'NO OK')], default='pending', max_length=50),
        ),
    ]
