# Generated by Django 5.1.7 on 2025-04-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_testresult_measured_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='tooltip_a',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='tooltip_b',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
