# Generated by Django 5.1.7 on 2025-05-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_testsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teststage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Terminado'), ('unmeasurable', 'No medible')], default='pending', max_length=20),
        ),
    ]
