# Generated by Django 5.1.7 on 2025-05-12 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_teststage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_port', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('pin_count', models.PositiveIntegerField()),
                ('connector_family', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RelayCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('bus', models.IntegerField()),
                ('device', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Adapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pxi_connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adapters_as_pxi', to='home.connectortype')),
                ('test_connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adapters_as_test', to='home.connectortype')),
            ],
        ),
        migrations.CreateModel(
            name='AdapterPinMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adapter_pin', models.PositiveIntegerField()),
                ('pxi_channel', models.PositiveIntegerField()),
                ('adapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adapter_name', to='home.adapter')),
                ('relay_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pxi_card', to='home.relaycard')),
            ],
            options={
                'unique_together': {('adapter', 'adapter_pin', 'pxi_channel')},
            },
        ),
    ]
