# Generated by Django 5.1.7 on 2025-05-13 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_connectionconfig_connectortype_relaycard_adapter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_type', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='adapter',
            name='pxi_connector',
        ),
        migrations.RemoveField(
            model_name='adapter',
            name='test_connector',
        ),
        migrations.RenameField(
            model_name='adapterpinmap',
            old_name='adapter_pin',
            new_name='test_pin',
        ),
        migrations.AlterField(
            model_name='adapterpinmap',
            name='relay_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_maps', to='home.relaycard'),
        ),
        migrations.CreateModel(
            name='AdapterConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='home.adapter')),
                ('pxi_connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_pxi_connections', to='home.physicalconnector')),
                ('test_connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_test_connections', to='home.physicalconnector')),
            ],
            options={
                'unique_together': {('adapter', 'test_connector', 'pxi_connector')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='adapterpinmap',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='adapterpinmap',
            name='adapter_connection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pin_maps', to='home.adapterconnection'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='adapterpinmap',
            unique_together={('adapter_connection', 'test_pin', 'relay_card', 'pxi_channel')},
        ),
        migrations.DeleteModel(
            name='ConnectorType',
        ),
        migrations.RemoveField(
            model_name='adapterpinmap',
            name='adapter',
        ),
    ]
