# Generated by Django 5.1.7 on 2025-05-14 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_physicalconnector_remove_adapter_pxi_connector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalconnector',
            name='adapter',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='physical_connectors', to='home.adapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='physicalconnector',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='physicalconnector',
            unique_together={('adapter', 'label')},
        ),
    ]
