# Generated by Django 5.1.7 on 2025-05-19 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_physicalconnector_adapter_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adapterconnection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='adapterconnection',
            name='adapter',
        ),
        migrations.RemoveField(
            model_name='adapterconnection',
            name='pxi_connector',
        ),
        migrations.RemoveField(
            model_name='adapterconnection',
            name='test_connector',
        ),
        migrations.AlterModelOptions(
            name='adapterpinmap',
            options={'ordering': ['adapter', 'pxi_connector', 'pxi_channel']},
        ),
        migrations.AlterModelOptions(
            name='physicalconnector',
            options={'ordering': ['adapter', 'label']},
        ),
        migrations.AlterUniqueTogether(
            name='adapterpinmap',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='adapterpinmap',
            name='adapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_maps', to='home.adapter'),
        ),
        migrations.AddField(
            model_name='adapterpinmap',
            name='pxi_channel_type',
            field=models.CharField(choices=[('U', 'Input'), ('M', 'Output')], default='U', max_length=50),
        ),
        migrations.AddField(
            model_name='adapterpinmap',
            name='pxi_connector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_maps_pxi', to='home.physicalconnector'),
        ),
        migrations.AddField(
            model_name='adapterpinmap',
            name='test_connector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_maps_test', to='home.physicalconnector'),
        ),
        migrations.AddField(
            model_name='physicalconnector',
            name='connector_side',
            field=models.CharField(choices=[('pxi-side', 'Lado PXI'), ('test-side', 'Lado test')], default='pxi-side', max_length=50),
        ),
        migrations.AddField(
            model_name='physicalconnector',
            name='pin_qty',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adapterpinmap',
            name='pxi_channel',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adapterpinmap',
            name='relay_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_maps_relay', to='home.relaycard'),
        ),
        migrations.AlterField(
            model_name='adapterpinmap',
            name='test_pin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='adapterpinmap',
            constraint=models.UniqueConstraint(fields=('adapter', 'pxi_connector', 'pxi_channel'), name='unique_pxi_mapping_per_adapter'),
        ),
        migrations.RemoveField(
            model_name='adapterpinmap',
            name='adapter_connection',
        ),
        migrations.DeleteModel(
            name='AdapterConnection',
        ),
    ]
