# Generated by Django 5.1.7 on 2025-05-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_adapterpinmap_pxi_channel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adapterpinmap',
            name='pxi_pin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
