# Generated by Django 5.1.7 on 2025-05-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_adapterpinmap_pxi_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adapterpinmap',
            old_name='pxi_pin',
            new_name='to_pxi_pin',
        ),
        migrations.RenameField(
            model_name='adapterpinmap',
            old_name='test_pin',
            new_name='to_test_pin',
        ),
    ]
