# Generated by Django 5.1.7 on 2025-05-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_pxi_pin_adapterpinmap_to_pxi_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adapterpinmap',
            name='pxi_channel_type',
            field=models.CharField(blank=True, choices=[('U', 'Input'), ('M', 'Output'), ('undefined', 'No definido')], default='undefined', max_length=50, null=True),
        ),
    ]
