# Generated by Django 5.1.7 on 2025-05-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_adapterpinmap_pxi_channel_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adapterpinmap',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='adapterpinmap',
            name='unique_pxi_mapping_per_adapter',
        ),
        migrations.AddConstraint(
            model_name='adapterpinmap',
            constraint=models.UniqueConstraint(fields=('adapter', 'relay_card', 'pxi_channel'), name='unique_pxi_mapping_per_adapter_and_relay'),
        ),
        migrations.AddConstraint(
            model_name='adapterpinmap',
            constraint=models.UniqueConstraint(fields=('adapter', 'test_connector', 'to_test_pin'), name='unique_test_mapping_per_adapter'),
        ),
    ]
