# Generated by Django 5.1.7 on 2025-05-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_adapterpinmap_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adapterpinmap',
            options={'ordering': ['adapter', 'relay_card', 'pxi_channel']},
        ),
    ]
